# Generated by Django 4.2.6 on 2023-10-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_verify_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify',
            name='verify_code',
            field=models.PositiveIntegerField(default=75440, verbose_name='verify code'),
        ),
    ]
