# Generated by Django 4.2.6 on 2023-10-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_verify_verify_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='chat id'),
        ),
        migrations.AlterField(
            model_name='verify',
            name='verify_code',
            field=models.PositiveIntegerField(default=68385, verbose_name='verify code'),
        ),
    ]
