# Generated by Django 4.2.6 on 2023-10-17 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('place', models.CharField(max_length=200, verbose_name='place')),
                ('action', models.TextField(verbose_name='action')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('lide_time', models.IntegerField(verbose_name='lide time')),
                ('period', models.PositiveIntegerField(default=1, verbose_name='period')),
                ('is_publish', models.BooleanField(blank=True, null=True, verbose_name='is publish')),
                ('task', models.PositiveIntegerField(default=0, verbose_name='periodic task')),
            ],
            options={
                'verbose_name': 'habit',
                'verbose_name_plural': 'habits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Nice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nise', to='habit.habit', verbose_name='habit')),
            ],
            options={
                'verbose_name': 'nice_habit',
                'verbose_name_plural': 'nice_habits',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_nice', models.BooleanField(blank=True, null=True, verbose_name='sign of a pleasant habit')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='reward')),
                ('habit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='habit.habit', verbose_name='habit')),
                ('nice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nice', to='habit.nice', verbose_name='habit')),
            ],
            options={
                'verbose_name': 'useful_habit',
                'verbose_name_plural': 'useful_habits',
            },
        ),
    ]
