# Generated by Django 4.2.6 on 2023-10-05 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('place', models.CharField(max_length=200, verbose_name='place')),
                ('action', models.TextField(verbose_name='action')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('lide_time', models.IntegerField(verbose_name='lead time')),
                ('period', models.PositiveIntegerField(choices=[('1', 'One day'), ('2', 'Two days'), ('3', 'Three days'), ('4', 'Four days'), ('5', 'Five days'), ('6', 'Six days'), ('7', 'Seven days')], default='1', verbose_name='period')),
                ('is_nice', models.BooleanField(blank=True, null=True, verbose_name='sign of a pleasant habit')),
                ('is_publish', models.BooleanField(blank=True, null=True, verbose_name='is publish')),
            ],
            options={
                'verbose_name': 'habit',
                'verbose_name_plural': 'habits',
            },
        ),
        migrations.CreateModel(
            name='Nice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nise', to='habit.habit', verbose_name='habit')),
            ],
            options={
                'verbose_name': 'nice_habit',
                'verbose_name_plural': 'nice_habits',
            },
        ),
        migrations.CreateModel(
            name='Useful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='reward')),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='useful', to='habit.habit', verbose_name='habit')),
                ('nice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nise', to='habit.nice', verbose_name='habit')),
            ],
            options={
                'verbose_name': 'useful_habit',
                'verbose_name_plural': 'useful_habits',
            },
        ),
    ]
