# Generated by Django 4.2.6 on 2023-10-06 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='reward')),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='habit.habit', verbose_name='habit')),
                ('nice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nice', to='habit.nice', verbose_name='habit')),
            ],
            options={
                'verbose_name': 'useful_habit',
                'verbose_name_plural': 'useful_habits',
            },
        ),
        migrations.DeleteModel(
            name='Useful',
        ),
    ]
