# Generated by Django 4.2.6 on 2023-10-06 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_reward_delete_useful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='habit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='habit.habit', verbose_name='habit'),
        ),
    ]
