# Generated by Django 4.2.6 on 2023-10-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_alter_reward_habit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='is_nice',
        ),
        migrations.AddField(
            model_name='reward',
            name='is_nice',
            field=models.BooleanField(blank=True, null=True, verbose_name='sign of a pleasant habit'),
        ),
    ]
