# Generated by Django 4.2.6 on 2023-10-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0005_remove_habit_is_nice_reward_is_nice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['name'], 'verbose_name': 'habit', 'verbose_name_plural': 'habits'},
        ),
    ]
