# Generated by Django 4.2.6 on 2023-10-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0007_alter_habit_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='task',
            field=models.PositiveIntegerField(default=0, verbose_name='periodic task'),
        ),
    ]
