# Generated by Django 4.2.6 on 2023-10-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0008_habit_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.PositiveIntegerField(default=1, verbose_name='period'),
        ),
    ]
