# Generated by Django 4.2.6 on 2023-10-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0009_alter_habit_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='lide_time',
            field=models.IntegerField(verbose_name='lide time'),
        ),
    ]
